#Use Node JS v16.x as base image
FROM node:latest

#create server directory inside image
WORKDIR /app

#copy the source code (src -> /app)
#node_modules directory is ignored via .dockerignore file
COPY . . 

#install dependencies (inside the container)
Run npm install 

#expose server port 
EXPOSE 3000

#Start server using npm script 
CMD ["npm", "run", "start"]
